- hosts: all
  sudo: True
  vars_files:
    - vars/users.yml
  roles:
    - essentials
    - mysql
    - memcached
    - redis

  handlers:
    - include: handlers.yml

- hosts: all
  sudo: False
  roles:
    - ruby
    - node

