- name: Install mysql
  apt: name={{ item }} state=present
  with_items:
    - mysql-server
    - libmysqlclient-dev
    - python-mysqldb
  tags:
    - mysql

- name: Create database user with name 'bob' and password '12345' with all database privileges
  mysql_user: name=root password='' priv=*.*:ALL host=% state=present
  tags:
    - mysql
    - unsafe

- name: Configure mysql for development. Enable access from outside (1)
  lineinfile: dest=/etc/mysql/my.cnf regexp="^bind-address\t\t= 192.168.56.11$" insertafter="^bind-address" line="bind-address  = 192.168.56.11" state=present
  tags:
    - mysql
    - unsafe

- name: Configure mysql for development. Enable access from outside (2)
  lineinfile: dest=/etc/mysql/my.cnf regexp="^bind-address\t\t= 127.0.0.1$" state=absent
  notify:
    - restart mysql
  tags:
    - mysql
    - unsafe
