- name: Install memcached essentials
  apt: name={{ item }} state=present
  with_items:
    - memcached
  sudo: true
  tags:
    - memcached

- name: Configure memcached for development. Enable access from outside (1)
  lineinfile: dest=/etc/memcached.conf regexp="^-l 0.0.0.0$" insertafter="^-l 127.0.0.1" line="-l 0.0.0.0" state=present
  tags:
    - memcached
    - unsafe

- name: Configure memcached for development. Enable access from outside (2)
  lineinfile: dest=/etc/mysql/my.cnf regexp="^-l 127.0.0.1" state=absent
  notify:
    - restart memcached
  tags:
    - memcached
    - unsafe

